### ISSUE TITLE
The pdf is corrupted and cannot be opened

### ISSUE THREAD

**Issue by Majosun** [yiyaowen/xdma_tutorial_win#1]
The pdf is corrupted and cannot be opened

**Comment by yiyaowen** [comment]
![image](https://github.com/yiyaowen/xdma_tutorial_win/assets/55590112/6e0c207f-1e29-4b49-b955-2b72b63268a1)
I can open it normally. The file is saved on Git-LFS. Have you checked that you can access Git-LFS properly?

**Comment by Majosun** [comment]
My God, thank you for your reply. I have listened to your advice, and I am trying to get it with Git-LFS, but the download has the following situation. Thank you very much again for your reply
![QQ截图20240511100058](https://github.com/yiyaowen/xdma_tutorial_win/assets/129364054/f922f0f1-c38f-4026-8cf6-a40b71991855)

**Comment by Majosun** [comment]
oh!! I got it! Thanks
![image](https://github.com/yiyaowen/xdma_tutorial_win/assets/129364054/db47cd96-935d-49da-b74e-c27c6b1ca480)
